#' Power calculation driven by coverage using simulated or user-supplied data
#'
#' Computes power as a function of coverage. Users can either:
#' \enumerate{
#'   \item Provide \code{sim_data} generated by \code{\link{sim_mod}} (no real data required), or
#'   \item Provide their own \code{filtered_data} (after merge/filter) plus phenotype labels,
#'         from which Mosasaur estimates baseline composition and then simulates datasets
#'         across a coverage grid.
#' }
#'
#' Power is defined as the fraction of truly affected CpGs detected at significance
#' threshold \code{alpha}. When using empirical data, “truth” is defined by the
#' simulation effect you specify (i.e., power is evaluated under a user-defined effect
#' size calibrated to real baseline rates).
#'
#' @param sim_data Optional data.frame produced by \code{\link{sim_mod}}.
#' @param filtered_data Optional filtered Mosasaur table (wide format) containing
#'   \code{Methyl_}, \code{Unmethyl_}, and optionally \code{Hydroxymethyl_} columns.
#' @param pheno Optional phenotype data.frame used with \code{filtered_data}.
#'   Must include sample IDs and group labels.
#' @param sample_id_col Column in \code{pheno} that matches sample IDs in the count table.
#' @param group_col Column in \code{pheno} indicating groups (must have 2 levels).
#' @param case_level Which level of \code{group_col} is treated as “case”.
#' @param contrast Which comparison to evaluate:
#'   \code{"methyl_vs_unmodified"} or \code{"hydroxy_vs_unmodified"}.
#' @param coverage_grid Integer vector of coverages to evaluate.
#' @param alpha Significance threshold used to compute power.
#' @param n_sims Number of simulation replicates per coverage point.
#' @param effect_delta Optional numeric effect shift for simulation when using empirical
#'   data (length 3: methylated, unmodified, hydroxymethylated). If NULL, a mild default
#'   is used.
#' @param effect_prop Proportion of CpG sites truly affected in simulations.
#' @param seed Optional integer seed for reproducibility.
#'
#' @details
#' Test model: for each CpG site, a quasibinomial GLM is fit:
#' \preformatted{
#' cbind(modified, total - modified) ~ group
#' }
#' using the selected contrast to define \code{modified}.
#'
#' @return A list with:
#' \describe{
#'   \item{summary}{data.frame of power by coverage}
#'   \item{raw}{optional per-simulation results}
#' }
#'
#' @examples
#' \dontrun{
#' # 1) No data: simulate then compute power
#' sim <- sim_mod(10, 10, 2000, m = 30,
#'                alpha = c(2, 10, 2),
#'                delta = c(2, -2, 0),
#'                effect_prop = 0.2, seed = 1)
#' pow <- power_calc(sim_data = sim,
#'                   contrast = "methyl_vs_unmodified",
#'                   coverage_grid = c(5, 10, 20, 30, 50),
#'                   n_sims = 20)
#'
#' # 2) Using your filtered data: estimate baseline, then simulate power vs coverage
#' pow2 <- power_calc(filtered_data = filtered,
#'                    pheno = pheno,
#'                    sample_id_col = "MATRR_ID",
#'                    group_col = "Group",
#'                    case_level = "HVHD",
#'                    contrast = "methyl_vs_unmodified",
#'                    coverage_grid = c(10, 20, 30, 40),
#'                    n_sims = 30)
#' }
#'
#' @export
power_calc <- function(
    sim_data = NULL,
    filtered_data = NULL,
    pheno = NULL,
    sample_id_col = "subject_id",
    group_col = "group",
    case_level = NULL,
    contrast = c("methyl_vs_unmodified", "hydroxy_vs_unmodified"),
    coverage_grid = c(5, 10, 20, 30, 50),
    alpha = 0.05,
    n_sims = 25,
    effect_delta = NULL,
    effect_prop = 1,
    seed = NULL
) {
  contrast <- match.arg(contrast)
  if (!is.null(seed)) set.seed(seed)

  site_pvals <- function(df_long) {
    cpgs <- unique(df_long$cpg_site)
    p <- numeric(length(cpgs))
    eff <- logical(length(cpgs))
    names(p) <- cpgs

    for (i in seq_along(cpgs)) {
      d <- df_long[df_long$cpg_site == cpgs[i], , drop = FALSE]
      eff[i] <- any(d$is_effect)

      fit <- try(
        stats::glm(
          cbind(modified, total - modified) ~ group,
          data = d,
          family = stats::quasibinomial()
        ),
        silent = TRUE
      )
      if (inherits(fit, "try-error")) {
        p[i] <- NA_real_
      } else {
        sm <- summary(fit)

        if (nrow(sm$coefficients) < 2) p[i] <- NA_real_ else p[i] <- sm$coefficients[2, 4]
      }
    }
    data.frame(cpg_site = cpgs, pvalue = p, is_effect = eff, stringsAsFactors = FALSE)
  }

  #build long table from sim_mod output
  sim_to_long <- function(sim, cov_target) {
    sim$total <- sim$methylated + sim$unmodified + sim$hydroxymethylated
    t <- pmin(cov_target, sim$total)

    if (contrast == "methyl_vs_unmodified") {
      mod_obs <- sim$methylated
    } else {
      mod_obs <- sim$hydroxymethylated
    }

    prob <- ifelse(sim$total > 0, mod_obs / sim$total, 0)
    modified <- stats::rbinom(nrow(sim), size = t, prob = prob)

    out <- data.frame(
      cpg_site = sim$cpg_site,
      group = factor(sim$group),
      modified = modified,
      total = t,
      is_effect = sim$is_effect
    )
    out
  }

  #estimate baseline alpha from empirical filtered table
  estimate_alpha_from_filtered <- function(filtered_data, pheno) {
    #build per-sample matrices by parsing column prefixes
    #assumes columns are named Methyl_<ID>, Unmethyl_<ID>, Hydroxymethyl_<ID>
    meth_cols <- grep("^Methyl_", names(filtered_data), value = TRUE)
    unm_cols  <- grep("^Unmethyl_", names(filtered_data), value = TRUE)
    hyd_cols  <- grep("^Hydroxymethyl_", names(filtered_data), value = TRUE)

    if (length(meth_cols) == 0 || length(unm_cols) == 0) {
      stop("filtered_data must contain Methyl_ and Unmethyl_ columns.")
    }
    if (length(hyd_cols) == 0) {
      #allow methyl-only data; hydroxy treated as 0 baseline
      filtered_data$.__hydroxy0 <- 0
      hyd_cols <- ".__hydroxy0"
    }

    # Align sample IDs
    ids_m <- sub("^Methyl_", "", meth_cols)
    ids_u <- sub("^Unmethyl_", "", unm_cols)
    common <- intersect(ids_m, ids_u)

    if (length(common) < 4) stop("Too few overlapping samples between Methyl_ and Unmethyl_ columns.")


    M <- as.matrix(filtered_data[, paste0("Methyl_", common), drop = FALSE])
    U <- as.matrix(filtered_data[, paste0("Unmethyl_", common), drop = FALSE])

    if (".__hydroxy0" %in% hyd_cols) {
      H <- matrix(0, nrow = nrow(M), ncol = ncol(M))
    } else {
      ids_h <- sub("^Hydroxymethyl_", "", hyd_cols)
      common_h <- intersect(common, ids_h)
      H <- as.matrix(filtered_data[, paste0("Hydroxymethyl_", common_h), drop = FALSE])
      if (ncol(H) != ncol(M)) {
        H2 <- matrix(0, nrow = nrow(M), ncol = ncol(M))
        colnames(H2) <- colnames(M)
        colnames(H) <- paste0("Methyl_", sub("^Hydroxymethyl_", "", colnames(H)))
        for (j in seq_len(ncol(H))) {
          nm <- colnames(H)[j]
          if (nm %in% colnames(H2)) H2[, nm] <- H[, j]
        }
        H <- H2
      }
    }

    total <- M + U + H
    pm <- mean(M / (total + 1e-9), na.rm = TRUE)
    pu <- mean(U / (total + 1e-9), na.rm = TRUE)
    ph <- mean(H / (total + 1e-9), na.rm = TRUE)


    scale_to <- 15
    base <- c(pm, pu, ph)
    base <- pmax(base, 1e-4)
    base <- base / sum(base)
    alpha_hat <- base * scale_to
    alpha_hat
  }

  #choose input mode
  if (is.null(sim_data) && is.null(filtered_data)) {
    stop("Provide either sim_data (from sim_mod) or filtered_data + pheno.")
  }

  if (!is.null(filtered_data)) {
    if (is.null(pheno)) stop("If filtered_data is provided, pheno must also be provided.")
    if (!(sample_id_col %in% names(pheno))) stop("sample_id_col not found in pheno.")
    if (!(group_col %in% names(pheno))) stop("group_col not found in pheno.")

    grp <- factor(pheno[[group_col]])
    if (nlevels(grp) != 2) stop("group_col must have exactly 2 levels for this power function.")
    if (is.null(case_level)) case_level <- levels(grp)[2]

    alpha_hat <- estimate_alpha_from_filtered(filtered_data, pheno)


    if (is.null(effect_delta)) {
      if (contrast == "methyl_vs_unmodified") {
        effect_delta <- c(2, -2, 0)
      } else {
        effect_delta <- c(0, -2, 2)
      }
    }
    if (length(effect_delta) != 3) stop("effect_delta must have length 3 (methyl, unmodified, hydroxy).")


    sim_data <- sim_mod(
      n_controls = sum(grp != case_level),
      n_cases = sum(grp == case_level),
      n_cpg = min(2000, nrow(filtered_data)),
      m = max(coverage_grid),
      alpha = alpha_hat,
      delta = effect_delta,
      effect_prop = effect_prop
    )
  } else {
    #sim_data mode
    needed <- c("methylated", "unmodified", "hydroxymethylated", "group", "cpg_site", "is_effect")
    miss <- setdiff(needed, names(sim_data))
    if (length(miss) > 0) stop("sim_data is missing columns: ", paste(miss, collapse = ", "))
  }

  results <- vector("list", length(coverage_grid))
  raw_out <- vector("list", length(coverage_grid))

  for (k in seq_along(coverage_grid)) {
    cov_target <- as.integer(coverage_grid[k])

    pow_sims <- numeric(n_sims)
    for (s in seq_len(n_sims)) {
      long <- sim_to_long(sim_data, cov_target = cov_target)
      ptab <- site_pvals(long)


      eff <- ptab$is_effect & !is.na(ptab$pvalue)
      if (sum(eff) == 0) {
        pow_sims[s] <- NA_real_
      } else {
        pow_sims[s] <- mean(ptab$pvalue[eff] <= alpha, na.rm = TRUE)
      }
    }

    results[[k]] <- data.frame(
      coverage = cov_target,
      power_mean = mean(pow_sims, na.rm = TRUE),
      power_sd = stats::sd(pow_sims, na.rm = TRUE),
      n_sims = n_sims
    )
    raw_out[[k]] <- data.frame(coverage = cov_target, sim = seq_len(n_sims), power = pow_sims)
  }

  summary <- do.call(rbind, results)
  raw <- do.call(rbind, raw_out)

  list(summary = summary, raw = raw)
}
